Add catch all case to fix match errors in VatNumberEligibilityService
hmrc/vat-sign-up pull request #324
Opened 2020-12-03 14:51 UTC by elliots41

2020-12-03 14:53 UTC, r-melvin commented on app/uk/gov/hmrc/vatsignup/httpparsers/VatCustomerDetailsHttpParser.scala
> +          s"[VatCustomerDetailsHttpParser] InvalidKnownFacts or other expection thrown, Response Status: ${response.status} Response Body: ${response.body}")
typo - expection should be exception?

2020-12-04 07:39 UTC, kabuumu requested changes

2020-12-04 07:39 UTC, kabuumu commented on app/uk/gov/hmrc/vatsignup/httpparsers/VatCustomerDetailsHttpParser.scala
> -          Left(InvalidKnownFacts(
If InvalidKnownFacts is no longer used, could we delete it?

2020-12-07 10:31 UTC, r-melvin approved these changes

2020-12-07 11:02 UTC, merged